### ISSUE TITLE
Small packaging bug in Release 1.3.0

### ISSUE THREAD

**Issue by hhromic** [bremeld/solr-undertow#17]
Hello,
I just discovered a small packaging bug in the latest release (1.3.0) that includes SOLR **4.10.4**. The included example config file ```example/example.conf``` references SOLR version *5.0.0* instead of **4.10.4**:

```
solr.undertow: {
  httpClusterPort: 8983
  solrHome: "./solr-home"
  solrLogs: "./solr-logs"
  tempDir: "./solr-temp"
  solrVersion: "5.0.0"   <-- should be "4.10.4"
  solrWarFile: ./solr-wars/solr-${solr.undertow.solrVersion}.war
}
```

Fixing this is very easy for the end-user but if they don't pay attention it might be hard to catch this. I double-checked the other SOLR versions (4.10.3 and 5.0.0) and their packages seems fine.

Cheers,
Hugo.

**Comment by apatrida** [comment]
current versions are fine.
