### ISSUE TITLE
Add socketfile support

### ISSUE THREAD

**Issue by iBobik** [bremeld/solr-undertow#18]
If Solr is on shared host we can not effectively hide it from other users if it listens on a port. Is it possible to configure Solr to listen on socket file? Or is there some other way how to secure if from other users on the same server?

Thanks for help.

**Comment by jaysonminard** [comment]
I do not see a way to bind to a socket file from Undertow (Wildfly doesn't list it either).

Can you use containers on the server, i.e. Docker?  They are a more *ahem* modern and low overhead way to isolate processes and environments on Unix systems.
