### ISSUE TITLE
Run as a Windows Service?

### ISSUE THREAD

**Issue by thomasreiser** [bremeld/solr-undertow#19]
Is there already a possibility to run solr-undertow as a Windows Service?

**Comment by jaysonminard** [comment]
Best bet is to use this to host it:
https://github.com/kohsuke/winsw

Or search google for "Java windows service wrapper" or "windows service wrapper" for alternatives, but that direct link above looks like a reasonable option.  If you look at the bin/solr-undertow.bat file you can see what parameters are set by default.

**Comment by thomasreiser** [comment]
Thank you, winsw works great for me!
