### ISSUE TITLE
Support for shutdown/restart commands

### ISSUE THREAD

**Issue by magicdude4eva** [bremeld/solr-undertow#22]
Why can undertow not support shutdown/restart functions as supported in Jboss CLI - i.e.

jboss-cli.sh --connect --command=:shutdown
jboss-cli.sh -c "/:shutdown()"
jboss-cli.sh -c /:shutdown
jboss-cli.sh -c :shutdown
jboss-cli.sh -c ":shutdown(restart=true)"

Undertow supports shutdown hooks - this guy has done it: http://blog.progs.be/704/executable-jar-with-embedded-web-server

**Comment by apatrida** [comment]
I can make the changes to the undertow host, it isn' that complicated for requesting a shutdown, and even redeploy of the contained Solr war.  Along with #21, this is related work.

**Comment by apatrida** [comment]
I added HTTP shutdown port and password, see release 1.4.0-RC1 and updated README with a shutdown section.  Also see issue #23 about the shutdown listener.

Still missing scripts.

**Comment by magicdude4eva** [comment]
Thanks - working perfectly fine.
