### ISSUE TITLE
Add shutdown port, so can receive a shutdown request via HTTP GET

### ISSUE THREAD

**Issue by apatrida** [bremeld/solr-undertow#23]
Added this, with default configuration:

```
  # Shutdown options
  shutdown: {
     httpPort: 9983
     httpHost: "0.0.0.0"
     # if password is not set, shutdown is not enabled.  Make this a secure password!
     password: ""
     gracefulDelay: "30s"
  }
```

If password is not configured, shutdown port will reject the request.  

from the updated README:

#### Restart / Shutdown

Solr-Undertow listens on the configured shutdown HTTP port (defaults to 9983) for a GET request, single parameter of `password` which must be set to a value matching the configured password.

If the a shutdown password is not configured then a 403 forbidden error will be returned.  If the password does not match, a 401 unauthorized error will be return.  Otherwise on success a 200 HTTP response, and on timeout or other error a 500 HTTP response (although the VM will still exit).  See the [configuration defaults file](src/main/resources/reference.conf) for the `shutdown` section.

**Comment by apatrida** [comment]
Added in 1.4.0-RC1 release

**Comment by magicdude4eva** [comment]
Awesome - thank you. Find my startup/shutdown scripts and JVM tuning options in this GIST for possible inclusion - https://gist.github.com/magicdude4eva/3b5fec150fbcaafdc34c

**Comment by apatrida** [comment]
Tracking your examples scripts as #25
